#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Antes de enviar seu codigo vou esta testando seu projeto antes de se comprometer'

npm run test:e2e ||
(
    echo '🤢🤮🤢🤮 É F**KING RAW - Seu teste e2e parece nojento.. 🤢🤮🤢🤮
    '
    false;
)

echo '🤔🤔🤔🤔... Tudo bem... O teste passou...  Vou tentando gerar a build agora. 🤔🤔🤔🤔'



# If everything passes... Now we can commit
echo '✅✅✅✅ Você venceu mais uma vez... Estou enviando seu codigo agora para o git. ✅✅✅✅

'
